POST http://localhost:8080/api/etudiant/
Content-Type: application/json


{
  "numEtudiant": "1234567890",
  "nom": "Dupont",
  "prenom": "Alice",
  "email": "alice.dupont@example.com",
  "codeBar": "0123456789012345",
  "groupe": {
    "numGroupe": "G001",
    "nom": "Groupe 1",
    "etudiants": []
  }
}

###
GET http://localhost:8080/api/etudiant
Accept: application/json



